#docker run -d -p 3000:8080 --add-host=host.docker.internal:host-gateway -v open-webui:/app/backend/data --name open-webui --restart always ghcr.io/open-webui/open-webui:main
version: '3'
services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    environment:
      - PORT=8888
      - OLLAMA_BASE_URL=http://127.0.0.1:11434
    volumes:
      - ./open-webui:/app/backend/data
    restart: always
    networks:
      - open-webui-network

networks:
  open-webui-network:
    driver: host